version: '3.8'

services:

  client:
    build:
      context: ./client
      target: development
    container_name: client_service
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app # Sincroniza el código para hot reload
      - /app/node_modules # Evita conflictos con node_modules
    depends_on:
      - backend
    networks:
      - app-network
    restart: always
    environment:
      - EVERY_MARKET_API_URL=http://localhost:5000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend_service
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/tmp:/app/tmp
    command: air
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=every_market
    networks:
      - app-network
    restart: always
    depends_on:
      - db
  
  db:
    image: postgres:15
    container_name: every_market_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: every_market
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
